image: python:3.9

stages:
  - run

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

scrape_and_update:
  stage: run
  script:
    - python scrape_and_update.py