# image: python:3.9

# stages:
#   - run

# before_script:
#   - python --version
#   - pip install --upgrade pip
#   - pip install -r requirements.txt

# scrape_and_update:
#   stage: run
#   script:
#     - python scrape_and_update.py


stages:
  - scrape

scrape_foreclosures:
  stage: scrape
  image: mcr.microsoft.com/playwright/python:v1.48.0-jammy
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "▶ Running foreclosure scraper..."
    - python main.py
  only:
    - main
  variables:
    GOOGLE_CREDENTIALS: "$GOOGLE_CREDENTIALS"
    SPREADSHEET_ID: "$SPREADSHEET_ID"
