# image: python:3.9

# stages:
#   - run

# before_script:
#   - python --version
#   - pip install --upgrade pip
#   - pip install -r requirements.txt

# scrape_and_update:
#   stage: run
#   script:
#     - python scrape_and_update.py




stages:
  - scrape

scrape_foreclosures:
  stage: scrape
  image: python:3.11-slim
  before_script:
    # Install system dependencies required by Playwright Chromium
    - apt-get update && apt-get install -y wget curl unzip git \
        libglib2.0-0 libnss3 libgdk-pixbuf2.0-0 libgtk-3-0 libx11-xcb1 \
        libdbus-1-3 libdrm2 libgbm1 libasound2 xvfb fonts-liberation libxshmfence1
    # Install Python deps
    - pip install --upgrade pip
    - pip install -r requirements.txt
    # Install Playwright browsers (Chromium)
    - playwright install --with-deps chromium
  script:
    - echo "▶ Running foreclosure scraper..."
    - python main.py
  only:
    - main
  variables:
    # These should be set in GitLab → Settings → CI/CD → Variables (masked & protected)
    GOOGLE_CREDENTIALS: "$GOOGLE_CREDENTIALS"
    SPREADSHEET_ID: "$SPREADSHEET_ID"
